# Generated by Django 2.0.2 on 2018-07-28 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_tuijianren'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='tuijianren',
        ),
    ]
