# Generated by Django 2.0.2 on 2018-08-02 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userprofile_tuijianren'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projects', models.CharField(max_length=128, verbose_name='资产项目')),
                ('ps', models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '资产项目',
                'verbose_name_plural': '资产项目',
                'db_table': 'AssetProject',
                'permissions': {('read_assetproject', '只读资产项目'), ('cmd_assetproject', '执行资产项目')},
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cunkuan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='资金'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Question'),
        ),
    ]
