# Generated by Django 2.0.2 on 2018-08-04 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_gongshangxinxi_ke_hu_xin_xi_shuinixinxi_zhuang_xie_gong_xin_xi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ke_hu_xin_xi',
            new_name='KeHuXinXi',
        ),
        migrations.AlterModelOptions(
            name='kehuxinxi',
            options={'verbose_name': '客户编号', 'verbose_name_plural': '客户编号'},
        ),
    ]
