# Generated by Django 2.0.2 on 2018-08-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20180804_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xiaoshoudengji',
            old_name='dian_hua2',
            new_name='ke_hu_ming_cheng',
        ),
        migrations.RenameField(
            model_name='xiaoshoudengji',
            old_name='ke_hu_bian_hao',
            new_name='si_ji',
        ),
        migrations.AddField(
            model_name='xiaoshoudengji',
            name='che_pai_hao',
            field=models.CharField(default='', max_length=200, verbose_name='车牌号'),
            preserve_default=False,
        ),
    ]
