# Generated by Django 2.0.2 on 2018-08-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20180804_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChanPinGuanLi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_pin_ming_chen', models.CharField(max_length=200, verbose_name='产品名称')),
                ('can_pin_miao_shu', models.CharField(max_length=200, verbose_name='产品描述')),
                ('can_pin_fu_ze_ren', models.CharField(max_length=200, verbose_name='产品负责人')),
            ],
            options={
                'verbose_name': '产品管理',
                'verbose_name_plural': '产品管理',
            },
        ),
        migrations.CreateModel(
            name='ChiXuJiaoFu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xiang_mu_ming', models.CharField(max_length=200, verbose_name='项目名')),
                ('xiang_mu_miaosu', models.CharField(max_length=200, verbose_name='项目描述')),
                ('ban_ben_xin_xi', models.CharField(max_length=200, verbose_name='版本信息')),
                ('shell', models.CharField(max_length=200, verbose_name='shell')),
            ],
            options={
                'verbose_name': '持续交付',
                'verbose_name_plural': '持续交付',
            },
        ),
        migrations.CreateModel(
            name='FuZeRen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fu_ze_ren', models.CharField(max_length=200, verbose_name='负责人姓名')),
                ('fu_ze_ren_shou_ji', models.CharField(max_length=200, verbose_name='负责人手机')),
                ('fu_ze_ren_qq', models.CharField(max_length=200, verbose_name='负责人qq')),
                ('fu_ze_ren_wechat', models.CharField(max_length=200, verbose_name='负责人微信')),
            ],
            options={
                'verbose_name': '负责人管理',
                'verbose_name_plural': '负责人管理',
            },
        ),
        migrations.CreateModel(
            name='GuanKuYuan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guan_ku_yuan', models.CharField(max_length=200, verbose_name='供商名称')),
            ],
            options={
                'verbose_name': '记账员',
                'verbose_name_plural': '记账员',
            },
        ),
        migrations.CreateModel(
            name='JiFangGuanLi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ji_fang_biao_shi', models.CharField(max_length=200, verbose_name='机房标识')),
                ('ji_fang_ming_chen', models.CharField(max_length=200, verbose_name='机房名称')),
                ('ji_fang_di_zhi', models.CharField(max_length=200, verbose_name='机房地址')),
                ('ji_fang_dian_hua', models.CharField(max_length=200, verbose_name='机房电话')),
                ('ke_hu_jing_li', models.CharField(max_length=200, verbose_name='客户经理')),
                ('yi_dong_dian_hua', models.CharField(max_length=200, verbose_name='移动电话')),
                ('ji_gui_xin_xi', models.CharField(max_length=200, verbose_name='机柜信息')),
                ('jie_ru_dai_kuan', models.CharField(max_length=200, verbose_name='接入带宽')),
                ('bei_zhu_xin_xi', models.CharField(max_length=200, verbose_name='备注信息')),
            ],
            options={
                'verbose_name': '机房管理',
                'verbose_name_plural': '机房管理',
            },
        ),
        migrations.CreateModel(
            name='JiZhangYuan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ji_zhang_yuan', models.CharField(max_length=200, verbose_name='供商名称')),
            ],
            options={
                'verbose_name': '记账员',
                'verbose_name_plural': '记账员',
            },
        ),
        migrations.CreateModel(
            name='ShuZuGuanLi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fu_wu_qi_zu', models.CharField(max_length=200, verbose_name='服务器组')),
                ('miao_su', models.CharField(max_length=200, verbose_name='描述')),
                ('ke_xuan_fu_wu_qi', models.CharField(max_length=200, verbose_name='可选择服务器')),
            ],
            options={
                'verbose_name': '机房管理',
                'verbose_name_plural': '机房管理',
            },
        ),
        migrations.CreateModel(
            name='XiangMuGuanLi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xiang_mu_ming_chen', models.CharField(max_length=200, verbose_name='项目名称')),
                ('xiang_mu_miao_su', models.CharField(max_length=200, verbose_name='项目描述')),
                ('yu_yan_lei_xing', models.CharField(max_length=200, verbose_name='语言类型')),
                ('cheng_xu_lei_xing', models.CharField(max_length=200, verbose_name='程序类型')),
                ('fu_wu_qi_lei_xing', models.CharField(max_length=200, verbose_name='服务器类型')),
                ('yuan_lei_xing', models.CharField(max_length=200, verbose_name='源类型')),
                ('yuan_di_zhi', models.CharField(max_length=200, verbose_name='源地址')),
                ('cheng_xu_bu_shu_lu_jing', models.CharField(max_length=200, verbose_name='程序部署路径')),
                ('pei_zhi_wen_jian', models.CharField(max_length=200, verbose_name='配置文件路径')),
                ('suo_su_chan_pin', models.CharField(max_length=200, verbose_name='所属产品')),
                ('xiang_mu_fu_ze_ren', models.CharField(max_length=200, verbose_name='项目负责人')),
                ('suo_zai_fu_wu_qi', models.CharField(max_length=200, verbose_name='所在服务器')),
            ],
            options={
                'verbose_name': '项目管理',
                'verbose_name_plural': '项目管理',
            },
        ),
        migrations.CreateModel(
            name='ZhuJiGuanLi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zu_ji_ming', models.CharField(max_length=200, verbose_name='主机名')),
                ('guan_li_ip', models.CharField(max_length=200, verbose_name='管理ip')),
                ('suo_zai_ji_fang', models.CharField(max_length=200, verbose_name='所在机房')),
                ('qi_ta_ip', models.CharField(max_length=200, verbose_name='其他ip')),
                ('zi_can', models.CharField(max_length=200, verbose_name='资产')),
                ('she_bei_lei_xing', models.CharField(max_length=200, verbose_name='设备类型')),
                ('she_bei_zhuang_tai', models.CharField(max_length=200, verbose_name='设备状态')),
                ('cao_zuo_xi_tong', models.CharField(max_length=200, verbose_name='操作系统')),
                ('she_bei_chang_shang', models.CharField(max_length=200, verbose_name='设备厂商')),
                ('shang_jia_shi_jian', models.CharField(max_length=200, verbose_name='上架时间')),
                ('cpu_xing_hao', models.CharField(max_length=200, verbose_name='CPU型号')),
                ('cpu_shu_liang', models.CharField(max_length=200, verbose_name='cpu数量')),
                ('nei_cun_da_xiao', models.CharField(max_length=200, verbose_name='内存大小')),
                ('ying_pan_xin_xi', models.CharField(max_length=200, verbose_name='硬盘信息')),
                ('SN_hao_ma', models.CharField(max_length=200, verbose_name='SN号码')),
                ('suo_zai_wei_zhi', models.CharField(max_length=200, verbose_name='所在位置')),
                ('bei_zhu_xin_xi', models.CharField(max_length=200, verbose_name='备注信息')),
            ],
            options={
                'verbose_name': '主机管理',
                'verbose_name_plural': '主机管理',
            },
        ),
    ]
