# Generated by Django 2.0.2 on 2018-08-11 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_chanpinguanli_chixujiaofu_fuzeren_guankuyuan_jifangguanli_jizhangyuan_shuzuguanli_xiangmuguanli_zhuj'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bei_zhu', models.CharField(max_length=200, verbose_name='备注')),
            ],
            options={
                'verbose_name': '域名',
                'verbose_name_plural': '域名',
            },
        ),
        migrations.CreateModel(
            name='DnsIp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ji_lu_zhi', models.CharField(max_length=200, verbose_name='记录值')),
                ('ip', models.CharField(max_length=200, verbose_name='ip')),
            ],
            options={
                'verbose_name': '负责人管理',
                'verbose_name_plural': '负责人管理',
            },
        ),
        migrations.AddField(
            model_name='dns',
            name='yu_ming',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.DnsIp', verbose_name='域名'),
        ),
    ]
