# Generated by Django 2.0.2 on 2018-08-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20180811_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnsip',
            name='zhu_ji_ji_lu',
            field=models.CharField(default='', max_length=200, verbose_name='主机记录'),
            preserve_default=False,
        ),
    ]
