# Generated by Django 2.0.2 on 2018-08-11 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_dnsip_zhu_ji_ji_lu'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnsip',
            name='yu_ming',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.Dns', verbose_name='域名'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dns',
            name='yu_ming',
            field=models.CharField(max_length=200, verbose_name='域名'),
        ),
    ]
