# Generated by Django 2.0.2 on 2018-08-11 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20180811_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dns',
            old_name='yu_ming',
            new_name='name',
        ),
    ]
