# Generated by Django 2.0.2 on 2018-08-17 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20180811_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZhuJiip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=200, verbose_name='机房地址')),
                ('ji_fang_dian_hua', models.CharField(max_length=200, verbose_name='机房电话')),
                ('ke_hu_jing_li', models.CharField(max_length=200, verbose_name='客户经理')),
                ('yi_dong_dian_hua', models.CharField(max_length=200, verbose_name='移动电话')),
                ('ji_gui_xin_xi', models.CharField(max_length=200, verbose_name='机柜信息')),
                ('jie_ru_dai_kuan', models.CharField(max_length=200, verbose_name='接入带宽')),
                ('bei_zhu_xin_xi', models.CharField(max_length=200, verbose_name='备注信息')),
            ],
            options={
                'verbose_name': '高防ip',
                'verbose_name_plural': '高防ip',
            },
        ),
        migrations.AddField(
            model_name='zhujiguanli',
            name='yu_ming',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.Dns', verbose_name='域名'),
            preserve_default=False,
        ),
    ]
