# Generated by Django 2.0.2 on 2018-08-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20180817_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=200, verbose_name='名称')),
                ('ji_fang_dian_hua', models.CharField(max_length=200, verbose_name='docker镜像')),
                ('ke_hu_jing_li', models.CharField(max_length=200, verbose_name='数量')),
                ('env', models.CharField(max_length=200, verbose_name='环境变量')),
                ('readiness', models.CharField(max_length=200, verbose_name='readiness')),
                ('liveness', models.CharField(max_length=200, verbose_name='liveness')),
                ('bei_zhu_xin_xi', models.CharField(max_length=200, verbose_name='备注信息')),
            ],
            options={
                'verbose_name': '创建pod',
                'verbose_name_plural': '创建pod',
            },
        ),
        migrations.CreateModel(
            name='Pod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=200, verbose_name='名称')),
                ('ji_fang_dian_hua', models.CharField(max_length=200, verbose_name='docker镜像')),
                ('ke_hu_jing_li', models.CharField(max_length=200, verbose_name='数量')),
                ('env', models.CharField(max_length=200, verbose_name='环境变量')),
                ('readiness', models.CharField(max_length=200, verbose_name='readiness')),
                ('liveness', models.CharField(max_length=200, verbose_name='liveness')),
                ('bei_zhu_xin_xi', models.CharField(max_length=200, verbose_name='备注信息')),
            ],
            options={
                'verbose_name': '创建pod',
                'verbose_name_plural': '创建pod',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=200, verbose_name='名称')),
                ('ji_fang_dian_hua', models.CharField(max_length=200, verbose_name='docker镜像')),
                ('ke_hu_jing_li', models.CharField(max_length=200, verbose_name='数量')),
                ('env', models.CharField(max_length=200, verbose_name='环境变量')),
                ('readiness', models.CharField(max_length=200, verbose_name='readiness')),
                ('liveness', models.CharField(max_length=200, verbose_name='liveness')),
                ('bei_zhu_xin_xi', models.CharField(max_length=200, verbose_name='备注信息')),
            ],
            options={
                'verbose_name': '创建pod',
                'verbose_name_plural': '创建pod',
            },
        ),
        migrations.CreateModel(
            name='RunDocker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=200, verbose_name='名称')),
                ('ji_fang_dian_hua', models.CharField(max_length=200, verbose_name='docker镜像')),
                ('ke_hu_jing_li', models.CharField(max_length=200, verbose_name='数量')),
                ('env', models.CharField(max_length=200, verbose_name='环境变量')),
                ('readiness', models.CharField(max_length=200, verbose_name='readiness')),
                ('liveness', models.CharField(max_length=200, verbose_name='liveness')),
                ('images', models.CharField(max_length=200, verbose_name='images')),
            ],
            options={
                'verbose_name': '创建pod',
                'verbose_name_plural': '创建pod',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=200, verbose_name='名称')),
                ('ji_fang_dian_hua', models.CharField(max_length=200, verbose_name='docker镜像')),
                ('ke_hu_jing_li', models.CharField(max_length=200, verbose_name='数量')),
                ('env', models.CharField(max_length=200, verbose_name='环境变量')),
                ('readiness', models.CharField(max_length=200, verbose_name='readiness')),
                ('liveness', models.CharField(max_length=200, verbose_name='liveness')),
                ('bei_zhu_xin_xi', models.CharField(max_length=200, verbose_name='备注信息')),
            ],
            options={
                'verbose_name': '创建服务',
                'verbose_name_plural': '创建服务',
            },
        ),
    ]
