# Generated by Django 2.0.2 on 2018-08-20 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_ingress_pod_project_rundocker_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rundocker',
            old_name='ip',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='rundocker',
            old_name='ke_hu_jing_li',
            new_name='Number',
        ),
        migrations.RemoveField(
            model_name='rundocker',
            name='ji_fang_dian_hua',
        ),
    ]
